// components/Layout.js
import Navbar from './Navbar';
import Head from "next/head";
import Container from 'react-bootstrap/Container';


export default function Layout({ children }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app and nazarenko" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
             {children}

        </>
    );
}
